# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a76959c6958263c5340a0ba516dbc441c1a01dc1a6589cffd6e0a851798ec8dd8de01ef90174e4a9ab11f3a6e860941d39100e5c975a110f16bba628b624369f

test:
  secret_key_base: bbb066d24e7dee6b6ea282245272005b716f250818465bc72f62f587e53edbb3a350f0ad688ae6c4350bc796877d560266129c845fb400a51ed4f06d3474fe59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
